apiVersion: v1
kind: Service
metadata:
  name: vkvs-service
  namespace: vkvs
spec:
  type: NodePort
  selector:
    app: vkvs
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000